### ISSUE TITLE
Mega-Upgrade Bug On Save and Resume

### ISSUE THREAD

**Issue by Frumgor** [Moocowsgomoo/StS-ConstructMod#28] opened 2018-12-04 13:12 UTC
I haven't tested yet to see if it's an issue inherent with the Construct mod or a compatibility issue with some other mod.  However, upon saving and resuming games, previously mega-upgraded cards become alternative upgrades that have applied the base upgrade logic twice it seems.  For example, Suppressive Fire++ becomes Suppressive Fire+2, dealing 9 damage and applying 1 Blur.  Similarly, Defense Mode++ becomes Defense Mode+2, with +4 Strength and -4 Dexterity.  Another side effect is that the cards become eligible for upgrades again but must be upgraded twice more in order to apply the mega upgrade effects.  The mods that I was running when this issue last occurred were as follows: The Construct, Infinite Spire, Conspire.

**Comment by Moocowsgomoo** [comment] 2018-12-09 03:24
This was caused by Conspire making patches to allow Infinite Journal to work. Fixed in the [latest release](https://github.com/Moocowsgomoo/StS-ConstructMod/releases) by giving mega-upgrades priority over Conspire's upgrade logic when loading a saved run. Thanks for the report!

**Closed as completed by Moocowsgomoo** 2018-12-09 03:24 UTC
